version: v2
managed:
  enabled: true
  override:
    - file_option: go_package_prefix
      value: github.com/moriba-cloud/skultem-gateway/infra/management/grpc/gen/go

plugins:
  - remote: buf.build/grpc/go
    out: gen/go
    opt:
      - paths=source_relative
      - require_unimplemented_servers=false
  - remote: buf.build/protocolbuffers/go
    out: gen/go
    opt: paths=source_relative